from modlunky2.mem.state import Theme

# List of tiles that will be included in the tile palette even if they do not already
# exist in the level file, since they are likely options to be used for the current theme.
def suggested_tiles_for_theme(theme, subtheme, include_common=True):
    common_tiles = [
        "floor",
        "empty",
        "floor%50",
        "minewood_floor",
        "floor_hard",
        "floor_hard%50%floor",
        "push_block",
        "ladder",
        "ladder_plat",
        "entrance",
        "exit",
        "door",
        "door2",
        "door2_secret",
        "locked_door",
        "treasure",
        "treasure_chest",
        "treasure_vaultchest",
    ]

    def theme_tiles(theme, subtheme=None):
        beehive_tiles = [
            "beehive_floor",
            "beehive_floor%50",
            "honey_upwards",
            "honey_downwards",
            "bee",
        ]
        if theme == Theme.DWELLING:
            return [
                "bone_block",
                "platform",
                "arrow_trap",
                "totem_trap",
                "spikes",
                "snake",
                "bat",
                "skeleton",
                "caveman",
                "caveman_asleep",
                "caveman_asleep%50",
                "scorpion",
                "mole",
                "lizard",
                "critter_dungbeetle",
                "cookfire",
                "turkey",
                "yang",
                "cavemanboss",
                "autowalltorch",
                "litwalltorch",
                "ghist_shopkeeper",
                "ghist_door2",
            ]
        elif theme == Theme.VOLCANA:
            return [
                "powder_keg",
                "timed_powder_keg",
                "falling_platform",
                "chain_ceiling",
                "chainandblocks_ceiling",
                "spikeball_trap",
                "conveyorbelt_left",
                "conveyorbelt_right",
                "factory_generator",
                "robot",
                "imp",
                "firebug",
                "caveman",
                "caveman_asleep",
                "lavamander",
                "bat",
                "vampire",
                "vlad",
                "oldhunter",
                "critter_snail",
                "lava",
                "vlad_floor",
                "nonreplaceable_babylon_floor",
                "drill",
                "udjat_socket",
                "slidingwall_switch",
                "slidingwall_ceiling",
                "crown_statue",
            ]
        elif theme == Theme.JUNGLE:
            return [
                "stone_floor",
                "vine",
                "growable_vine",
                "spikes",
                "bush_block",
                "thorn_vine",
                "jungle_spear_trap",
                "tree_base",
                "cookfire",
                "caveman",
                "mantrap",
                "witchdoctor",
                "tikiman",
                "mosquito",
                "giant_spider",
                "hangspider",
                "bat",
                "monkey",
                "critter_butterfly",
                "snap_trap",
            ] + beehive_tiles
        elif theme == Theme.OLMEC:
            return [
                "stone_floor",
                "crate_parachute",
                "storage_guy",
                "storage_floor",
                "autowalltorch",
                "olmec",
                "ankh",
                "pillar",
                "critter_crab",
                "critter_locust",
            ]
        elif theme == Theme.TIDE_POOL:
            return [
                "pagoda_floor",
                "pagoda_floor%50%floor",
                "climbing_pole",
                "growable_climbing_pole",
                "pagoda_platform",
                "spikes",
                "bone_block",
                "powder_keg",
                "water",
                "jiangshi",
                "assassin",
                "octopus",
                "hermitcrab",
                "crabman",
                "flying_fish",
                "critter_fish",
                "critter_anchovy",
                "critter_crab",
                "giantclam",
                "fountain_head",
                "fountain_drain",
                "slidingwall_switch",
                "slidingwall_ceiling",
                "minewood_floor",
                "excalibur",
                "excalibur_stone",
                "haunted_corpse",
            ]
        elif theme == Theme.ABZU:
            return theme_tiles(Theme.TIDE_POOL) + ["kingu"]
        elif theme == Theme.TEMPLE:
            return [
                "quicksand",
                "temple_floor",
                "temple_floor%50",
                "pot",
                "crushtrap",
                "crushtraplarge",
                "catmummy",
                "cobra",
                "crocman",
                "anubis",
                "mummy",
                "sorceress",
                "necromancer",
                "critter_locust",
            ] + beehive_tiles
        elif theme == Theme.ICE_CAVES:
            return [
                "minewood_floor",
                "icefloor",
                "icefloor%50",
                "spikes",
                "upsidedown_spikes",
                "falling_platform",
                "thinice",
                "spring_trap",
                "forcefield",
                "timed_forcefield",
                "forcefield_top",
                "litwalltorch",
                "autowalltorch",
                "cookfire",
                "landmine",
                "storage_guy",
                "storage_floor",
                "eggplant_altar",
                "moai_statue",
                "eggplant_child",
                "mothership_floor",
                "plasma_cannon",
                "alienqueen",
                "shopkeeper_vat",
                "alien_generator",
                "alien",
                "ufo",
                "yeti",
                "empty_mech",
                "critter_penguin",
                "critter_firefly",
            ]
        elif theme == Theme.NEO_BABYLON:
            return [
                "babylon_floor",
                "babylon_floor%50%floor",
                "laser_trap",
                "spark_trap",
                "forcefield",
                "timed_forcefield",
                "forcefield_top",
                "elevator",
                "zoo_exhibit",
                "litwalltorch",
                "mushroom_base",
                "lava",
                "lava%50%floor",
                "lamassu",
                "olmite",
                "ufo",
                "empty_mech",
                "critter_drone",
                "ushabti",
                "palace_floor",
                "palace_entrance",
                "palace_table",
                "palace_table_tray",
                "palace_chandelier",
                "palace_candle",
                "palace_bookcase",
                "stone_floor",
                "bone_block",
                "madametusk",
                "bodyguard",
            ]
        elif theme == Theme.TIAMAT:
            return [
                "babylon_floor",
                "babylon_floor%50%floor",
                "laser_trap",
                "spark_trap",
                "forcefield",
                "timed_forcefield",
                "forcefield_top",
                "elevator",
                "tiamat",
                "olmecship",
            ]
        elif theme == Theme.SUNKEN_CITY or theme == Theme.HUNDUN:
            return [
                "sunken_floor",
                "sunken_floor%50",
                "spikes",
                "pipe",
                "regenerating_block",
                "bigspear_trap",
                "bone_block",
                "sticky_trap",
                "storage_guy",
                "storage_floor",
                "autowalltorch",
                "mother_statue",
                "eggplant_door",
                "giant_frog",
                "guts_floor",
                "water",
                "frog",
                "firefrog",
                "tadpole",
                "giantfly",
                "critter_slime",
                "skull_drop_trap",
                "eggsac",
            ]
        elif theme == Theme.CITY_OF_GOLD:
            return [
                "quicksand",
                "cog_floor",
                "cog_floor%50",
                "crushtrap",
                "crushtraplarge",
                "slidingwall_switch",
                "slidingwall_ceiling",
                "crocman",
                "leprechaun",
                "mummy",
                "cobra",
                "sorceress",
                "critter_locust",
            ]
        elif theme == Theme.DUAT:
            return [
                "duat_floor",
                "duat_floor%50",
                "chain_ceiling",
                "lava",
                "ammit%50",
                "crocman",
                "snake",
                "cobra",
                "osiris",
                "anubis2",
            ]
        elif theme == Theme.EGGPLANT_WORLD:
            return [
                "pagoda_floor",
                "pagoda_floor%50",
                "pagoda_platform",
                "slidingwall_switch",
                "slidingwall_ceiling",
                "fountain_head",
                "fountain_drain",
                "water",
                "vine",
                "growable_vine",
                "jumpdog",
                "minister",
                "yama",
                "empress_grave",
            ]
        elif theme == Theme.COSMIC_OCEAN:
            return theme_tiles(subtheme) + ["cosmic_orb", "cosmic_jelly"]
        return []

    if include_common:
        return common_tiles + theme_tiles(theme, subtheme)
    else:
        return theme_tiles(theme, subtheme)
