name: Rust testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "src/modlunky2/**"
      - "src/tests/**"
      - "requirements*.txt"

jobs:
  build:
    name: "Rust ${{matrix.rust}}"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        # Test stable and MSRV
        rust: [stable, "1.64"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: clippy rustfmt
      - name: cargo check
        run: cargo check --workspace --all-targets --exclude launcher --locked
      - name: cargo fmt
        run: cargo fmt --all --check
      - name: cargo clippy
        run: cargo clippy --workspace --all-targets --exclude launcher --locked -- -D warnings
      - name: cargo test
        run: cargo test --workspace --all-targets --exclude launcher --locked
